[add] logger modification & fix error box creation
vivitek/box pull request #79
Opened 2021-05-14 16:04 UTC by Psyroo

## Fix box creation error
----

## Details

- fix error during box creation
- fix logger

2021-05-14 16:37 UTC, matfire requested changes

2021-05-14 16:37 UTC, matfire commented on graphql/index.ts
>      id = res.data.data.createRouter._id
pretty sure this crashes when undefined: use ?.

2021-05-14 16:43 UTC, matfire approved these changes

2021-05-16 10:58 UTC, thmarinho requested changes

2021-05-16 10:58 UTC, thmarinho commented on graphql/index.ts
> +    const resp = await axios({
unused var

2021-05-17 15:43 UTC, Psyroo commented on graphql/index.ts
> +    const resp = await axios({
done

2021-05-17 16:54 UTC, thmarinho approved these changes

2021-05-17 16:55 UTC, merged